apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "fraud-detection"
  namespace: default
spec:
  predictor:
    serviceAccountName: fraud-service-account
    storageUri: "s3://credit-card-fraud-mlops-bucket/model/" 
    containers:
      - name: kserve-container
        # Keep the LATEST tag the bot created (or yours, the CI will update it again anyway)
        image: 734367008253.dkr.ecr.ap-south-1.amazonaws.com/fraud-inference:v1.0.14
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: MODEL_PATH
            value: "/mnt/models/model.joblib"
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"