apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secrets
type: Opaque
stringData:
  BACKEND_STORE_URI: postgresql://mlflow:mlflow123@<RDS-ENDPOINT>:5432/mlflow
  ARTIFACT_ROOT: s3://fraud-mlops-mlflow-artifacts