apiVersion: apps/v1
kind: Deployment
metadata:
  name: openobserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openobserve
  template:
    metadata:
      labels:
        app: openobserve
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: openobserve
          image: public.ecr.aws/zinclabs/openobserve:latest
          ports:
            - containerPort: 5080