apiVersion: serving.kserve.io/v1beta1
kind: InferenceService

metadata:
  name: fraud-detection
  namespace: default

spec:
  predictor:
    serviceAccountName: fraud-service-account

    containers:
      - name: kserve-container
        image: 734367008253.dkr.ecr.ap-south-1.amazonaws.com/fraud-inference:v1.0.13

        ports:
          - containerPort: 8080

        env:
          - name: MODEL_PATH
            value: /app/model.joblib