apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: fraud-detection
spec:
  predictor:
    containers:
      - name: fraud-container
        image: fraud-inference:latest
        ports:
          - containerPort: 8080
        env:
          - name: MODEL_PATH
            value: /app/models/model.joblib