name: Training Image Build (DevSecOps + OIDC)

on:
  push:
    branches: [main]
    paths:
      - "src/training/**"
      - "docker/training.Dockerfile"
      - "requirements.txt"

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      security-events: write

    env:
      AWS_REGION: ap-south-1
      ACCOUNT_ID: "734367008253"
      ECR_REPO: fraud-training

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Nuke pyproject.toml for Snyk
        run: rm -f pyproject.toml || true

      - name: Snyk Security Scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=requirements.txt --package-manager=pip --severity-threshold=high

      - name: Checkov IaC Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: dockerfile
          quiet: true
          skip_check: CKV_DOCKER_2,CKV_DOCKER_3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login \
          --username AWS \
          --password-stdin ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Set Image Tag
        id: vars
        run: |
          TAG=v1.0.${{ github.run_number }}
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Build Image
        run: |
          docker build -f docker/training.Dockerfile \
            -t ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ steps.vars.outputs.TAG }} .

      - name: Trivy Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ steps.vars.outputs.TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Image
        run: |
          docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ steps.vars.outputs.TAG }}